# To build and launch (first time):
#   $ docker-compose up -d
# To create new images (--no-cache) to force building from scratch:
#   $ docker-compose build
# To launch again (leave out -d for non daemon launch):
#   $ docker-compose up -d
# To stop containers:
#  $ docker-compose stop
version: '3'
services:
  webgme-server:
    build:
      context: .
    depends_on:
    - mongo
    environment:
    - NODE_ENV=docker
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - database
      - server
    ports:
    # Change the LHS to map to other port on host
    - 8888:8888
  mongo:
    image: mongo:3.4.1
    ports:
    - 27017:27017 # Uncomment to expose mongo-port on host
    networks:
    - database
  py-core-executor:
    build:
      context: .
      dockerfile: DockerfilePyCoreExecutor
    depends_on:
    - webgme-server
    networks:
    - server
    environment:
    - NODE_ENV=docker
    command: ["cat", "/dev/null"] # A no-op command so the image is built.