/*globals define, _, WebGMEGlobal*/
/*jshint browser: true*/
/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Wed Nov 30 2016 10:36:41 GMT-0600 (Central Standard Time).
 */

define([
    'js/PanelBase/PanelBase',
    'js/PanelManager/IActivePanel',
    'widgets/ICore/ICoreWidget',
    './ICoreControl',
    'js/Utils/ComponentSettings',
    'text!./ICoreDefaultConfig.json'
], function (
    PanelBaseWithHeader,
    IActivePanel,
    ICoreWidget,
    ICoreControl,
    ComponentSettings,
    ICoreDefaultConfig) {

    'use strict';

    var ICorePanel;

    ICorePanel = function (layoutManager, params) {
        var options = {};
        //set properties from options
        options[PanelBaseWithHeader.OPTIONS.LOGGER_INSTANCE_NAME] = 'ICorePanel';
        options[PanelBaseWithHeader.OPTIONS.FLOATING_TITLE] = true;

        //call parent's constructor
        PanelBaseWithHeader.apply(this, [options, layoutManager]);

        this._client = params.client;
        this._config = ICorePanel.getDefaultConfig();
        ComponentSettings.resolveWithWebGMEGlobal(this._config, ICorePanel.getComponentId());

        //initialize UI
        this._initialize();

        this.logger.debug('ctor finished');
    };

    //inherit from PanelBaseWithHeader
    _.extend(ICorePanel.prototype, PanelBaseWithHeader.prototype);
    _.extend(ICorePanel.prototype, IActivePanel.prototype);

    ICorePanel.getComponentId = function () {
        return 'ICorePanel';
    };

    ICorePanel.getDefaultConfig = function () {
        return JSON.parse(ICoreDefaultConfig);
    };

    ICorePanel.prototype._initialize = function () {
        var self = this;

        this.widget = new ICoreWidget(this.logger, this.$el, this._config, ICorePanel.getComponentId());

        this.control = new ICoreControl({
            logger: this.logger,
            client: this._client,
            widget: this.widget,
            config: this._config,
            configId: ICorePanel.getComponentId()
        });

        this.onActivate();
    };

    /* OVERRIDE FROM WIDGET-WITH-HEADER */
    /* METHOD CALLED WHEN THE WIDGET'S READ-ONLY PROPERTY CHANGES */
    ICorePanel.prototype.onReadOnlyChanged = function (isReadOnly) {
        //apply parent's onReadOnlyChanged
        PanelBaseWithHeader.prototype.onReadOnlyChanged.call(this, isReadOnly);
    };

    ICorePanel.prototype.onResize = function (width, height) {
        this.logger.debug('onResize --> width: ' + width + ', height: ' + height);
        this.widget.onWidgetContainerResize(width, height);
    };

    /* * * * * * * * Visualizer life cycle callbacks * * * * * * * */
    ICorePanel.prototype.destroy = function () {
        this.control.destroy();
        this.widget.destroy();

        PanelBaseWithHeader.prototype.destroy.call(this);
        WebGMEGlobal.Toolbar.refresh();
    };

    ICorePanel.prototype.onActivate = function () {
        this.widget.onActivate();
        this.control.onActivate();
        WebGMEGlobal.Toolbar.refresh();
    };

    ICorePanel.prototype.onDeactivate = function () {
        this.widget.onDeactivate();
        this.control.onDeactivate();
        WebGMEGlobal.Toolbar.refresh();
    };

    return ICorePanel;
});
